### ISSUE TITLE
Installation not clear enought

### ISSUE THREAD

**Issue by noraj1337** [mcpa-stlouis/hack-the-arch#17]
Is it possible to create a clear installation guide because the README lacks the following points:
+ `pacman -S postgresql` or whatever but postgresql installed needed
+ `gem install bundler`
+ `blundle install`
+ `rails db:migrate` before `bundle exec rake db:seed`

Then we it's not clear that we need to go in `OfflineSetup` and launch `start_local`.

**Comment by paullj1** [comment]
Please reference the [Docker Readme](https://github.com/mcpa-stlouis/hack-the-arch/blob/master/DOCKER_README.md).

**Comment by noraj1337** [comment]
OK, I assume local install is deprecated so I tried the docker but see https://github.com/mcpa-stlouis/hack-the-arch/issues/21
