### ISSUE TITLE
[Request] hack-the-arch working with other databases

### ISSUE THREAD

**Issue by noraj1337** [mcpa-stlouis/hack-the-arch#18]
Is it possible to make hack-the-arch working with other databases (than postgresql) like mariadb?

**Comment by anpseftis** [comment]
It is possible I took this project and made it work with Mariadb

**Comment by paullj1** [comment]
Thanks @anpseftis!  Was it as easy as configuring the ORM in config/database.yml?  I've never tried to do this, but in theory it should be pretty easy.

**Comment by anpseftis** [comment]
It been a while but I believe that all I had to do was change the information in the database.yml file.
