### ISSUE TITLE
docker-compose error

### ISSUE THREAD

**Issue by noraj1337** [mcpa-stlouis/hack-the-arch#21]
Seems there is an error or a step is missing in [DOCKER_README.md](https://github.com/mcpa-stlouis/hack-the-arch/blob/dev/DOCKER_README.md) ?

```
docker-compose up -d
Creating network "hackthearch201_default" with the default driver
Creating volume "hackthearch201_hta" with default driver
Creating volume "hackthearch201_redis" with default driver
Creating volume "hackthearch201_postgres" with default driver
Pulling rd (redis:3.2)...
ERROR: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

If I directly access https://registry-1.docker.io/v2/ it says I need to be authenticated, why?
```
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}
```

**Comment by paullj1** [comment]
I've never had that issue. Which version of the docker engine and compose
are you running?

**Comment by noraj1337** [comment]
@paullj1 

```
$ docker --version
Docker version 17.04.0-ce, build 4845c567eb
$ docker-compose --version
docker-compose version 1.11.2, build dfed245b
```

**Comment by paullj1** [comment]
Thanks.  I'll try to look into it this evening.

**Comment by paullj1** [comment]
Try upgrading docker-compose to 1.12 in the meantime.

**Comment by paullj1** [comment]
So, I couldn't reproduce.  Are you using a fresh docker install?

**Comment by noraj1337** [comment]
@paullj1 : Yes I installed it in order to install HTA

**Comment by paullj1** [comment]
This may be a stupid question, but does the machine have access to the internet?  The reason I ask is because it doesn't look like you can pull the images.  If you don't, you can always pull the images necessary somewhere else, then export them to a tarball: `docker save IMAGE > image.tar`, then import with: `docker load image.tar`.

**Comment by noraj1337** [comment]
@paullj1 Oh wait. This machine has access to Internet but through a proxy and I remember docker need a special configuration for proxy (in order for example to be able to do pull).
