### ISSUE TITLE
[Request] regex flag support

### ISSUE THREAD

**Issue by noraj** [mcpa-stlouis/hack-the-arch#27]
Currently there is only one type of answer supported: string flags.
But it could be very nice to support also regex flag to allow multiple flags or a range of answers.

RootTheBox project use them if you need.

**Comment by paullj1** [comment]
Sorry for the delay.  Beta release coming soon, we'd appreciate any feedback you've got!

**Comment by noraj** [comment]
Using dev branch.
With an admin account, going in *Create Problem*.
I have a weird display:
![](https://i.imgur.com/PpOXO0a.png)

Also i did a very basic regex test and it worked well. We just need to know that we do not need to put the slashes like that`/regex/`. Is it possible to put the slashes before and after the area ? It will be more clear.

**Comment by paullj1** [comment]
So the slashes are usually a programming specific thing.  Every time you use `grep`, you're using regular expressions, and you never use slashes there.

The display issue seems to affect some browsers, and is documented in #47
