### ISSUE TITLE
[Question] Maximum number of submissions per team

### ISSUE THREAD

**Issue by noraj1337** [mcpa-stlouis/hack-the-arch#29]
In the *Scoring* menu (admin view), **Maximum number of submissions per team** value is per challenge or for all the CTF duration?

**Comment by paullj1** [comment]
That's correct.  That way it could be used for short-duration evaluation type event.

**Comment by noraj1337** [comment]
So the answer is: Maximum number of submissions per team for all the CTF duration?

**Comment by paullj1** [comment]
Correct.

**Comment by noraj1337** [comment]
Is is possible to write this precision under the field?

**Comment by paullj1** [comment]
@noraj1337, let me know if that is sufficient.

**Comment by noraj1337** [comment]
Here you put *per challenge* and last time you told me *for all the CTF duration* so I don't understand the final answer

**Comment by paullj1** [comment]
Per challenge, for the duration of the CTF. Is that any clearer?

**Comment by noraj1337** [comment]
@paullj1 yes it is :)
