### ISSUE TITLE
Update to a more recent version of ruby

### ISSUE THREAD

**Issue by noraj** [mcpa-stlouis/hack-the-arch#33]
After install ruby 2.3.1(used in [release v 2.0.1](https://github.com/mcpa-stlouis/hack-the-arch/releases/tag/v2.0.1)) with rvm I get the following warning:

```
Install of ruby-2.3.1 - #complete 
Please be aware that you just installed a ruby that requires 2 patches just to be compiled on an up to date linux system.
This may have known and unaccounted for security vulnerabilities.
Please consider upgrading to ruby-2.4.2 which will have all of the latest security patches.
```

**Comment by noraj** [comment]
#37 brought ruby 2.5 support, I need to try that.

**Comment by noraj** [comment]
I tested dev branch with ruby 2.5.1, install works well.

**Comment by paullj1** [comment]
No issues heard after release.  Closing.
