### ISSUE TITLE
Functionality of Brackets

### ISSUE THREAD

**Issue by stormctf** [mcpa-stlouis/hack-the-arch#36]
I sent the devs an email, but I thought it would be proper to open a ticket on the repo as well.

Currently our CTF platform is Mellivora that has been slightly modified to utilize the User Types functionality to only display Challenges based on the User Type. I wonder if HTA has this capability, or if it would be easily implemented. I have very little Ruby experience, otherwise I would do it myself. Any insight is appreciated.

**Comment by paullj1** [comment]
That’s not a bad idea, and probably wouldn’t take that long to implement.
I’ll see what I can do this weekend.

**Comment by paullj1** [comment]
Okay, so after spending some time thinking about this, I'm a little concerned that adding this feature may complicate the challenge creation process a little too much.  Why not make all challenges available to all users, and then offer hints to the less experienced users to allow them to compete with the more experienced users?  Thoughts?

**Comment by stormctf** [comment]
We create challenges specifically for the learner's and give them
walkthroughs. It would compromise the competition if the learner's had
access to those challenges' walkthroughs.

**Comment by paullj1** [comment]
So the point of the brackets (as is) is to allow you to offer those walkthroughs in chunks (hints) at an optional and configurable cost.  That way, if people are able to solve the challenge without them, they're rewarded with more points.  Each hint has a configurable number of points that will be deducted either before the challenge is solved (which will affect the players current score), or after the challenge is solved (which affects the value of the solve).

I'm not saying that what you're proposing is invalid, just that it would really complicate the existing design, and that I'm not sure about the best way to implement it.  Does that make sense?

**Comment by stormctf** [comment]
I definitely understand your point of view, but what stops the competitors
from registering a bogus account and clicking the hints to solve for their
true account?

**Comment by paullj1** [comment]
That has definitely been a concern.  Current mitigation strategy is to authorize all accounts where this could happen.  Latest release (under the e-mail tab in settings) allows for this.  If enabled, each account requires authorization by an admin before being activated.

**Comment by stormctf** [comment]
Unfortunately that mitigation does not work for us.

**Comment by paullj1** [comment]
So I'll leave this open as a discussion point for now.  Again, I'm just not sure how to cleanly implement it at the moment, but I'm definitely open to suggestions.

**Comment by stormctf** [comment]
Honestly a checkbox in the main settings marked "different challenges per
bracket" would do it

Then if that check box is marked have a new multi select box in the
category creation/edit page that lets you select which brackets to allow.
This makes the whole thing optional.

**Comment by paullj1** [comment]
Sure, implementation on the front-end is easy (ish... still, I think an argument could be made that it's getting more and more complex).  It's the back-end that gets a little messy... of course, that could be a sign that the project could use a massive refactoring, but I really don't have time for that right now.

Still, I agree.  If it is to be implemented, it must be optional.

**Comment by paullj1** [comment]
The feature that was implemented does not appear to have any issues.  Closing the ticket for now, feel free to open back up if you come up with a solution.

**Comment by stormctf** [comment]
Just to keep up, we ended up creating a Bracket plugin for CTFd that supported our needs. We definitely appreciate the work!
