### ISSUE TITLE
Hints can only be a max of 1000 points

### ISSUE THREAD

**Issue by JRWR** [mcpa-stlouis/hack-the-arch#38]
hack-the-arch/app/models/hint.rb
 validates :points, presence: true, inclusion: { in: 0..1000 }

I'm editing it for my CTF (Since our points per challenge are maxing out at 25k) -- The error message it returns is completely unhelpful as well with (Points is not in the list)

**Comment by paullj1** [comment]
No issues heard after release.  Closing.
