### ISSUE TITLE
Hints Display overflow and spam

### ISSUE THREAD

**Issue by JRWR** [mcpa-stlouis/hack-the-arch#42]
If you enter a very long hint it causes the hint display box to not expand correctly or wrap the text.
also noticed that hint_table is included more then once on the page, I'm up to about 120 challenges and its not uncommon for the entire page to start hard locking in chrome or firefox as a admin.

**Comment by JRWR** [comment]
![image](https://user-images.githubusercontent.com/804052/36262650-1206e5ca-1236-11e8-80ee-d2ce9e764cc6.png)

Also should note that adding hints is a little bit of a process, it seems like it was built for more using a hint for more then one challenge.

**Comment by paullj1** [comment]
@JRWR, this is an easy fix, and I can implement it for the next release.  Also, you're absolutely correct... it was built with using a hint for more than one challenge in mind, but not as the primary use case.  We had several challenges that didn't have any hints, so we created one "hint" that said there weren't any hints and didn't deduct any points, then re-used it everywhere.  The implementation could be better for sure, I just honestly haven't put that much thought into it.  Any suggestions?

**Comment by paullj1** [comment]
@JRWR Having trouble replicating.  Which browser are you seeing the overflow in?

**Comment by JRWR** [comment]
Google Chrome is up to date
Version 64.0.3282.167 (Official Build) (64-bit)

Win10

**Comment by paullj1** [comment]
Yeah, I got it.  Sorry.  That part is fixed.  I might need to spend some time thinking about how to *not* include the hint table for each challenge.  Currently, the buttons are hard coded to each challenge, so when you click "Add" on the hint, it goes to the challenge from which you opened the modal.  I'm looking at turning on fragment caching for your #43, which may fix it, but isn't ideal.

**Comment by JRWR** [comment]
So simplify the input of hints where in the hints admin its just a open
form fields for Hint Text and a ajax submission, load the form only when
the admin switches to the hint tab for that challenge, keep it where you
don't need to go off page to add a hint. quick and easy :)

Also, I noticed it doesn't show how many points are needed for a hint to
the end user

**Comment by paullj1** [comment]
Last commit actually was for #44.  Sorry for the confusion.
