### ISSUE TITLE
Let Encrypt for SSL and Docker

### ISSUE THREAD

**Issue by JRWR** [mcpa-stlouis/hack-the-arch#46]
Just another suggestion, Built-In lets encrypt, just set the hostname in the .env and a flag to turn on lets encrypt

acme.sh is a pretty good base for this.

**Comment by paullj1** [comment]
When I designed the app, Let's Encrypt was very nascent.  Consequently, I ended up just using CloudFlare for free SSL proxy-ing.  I appreciate the suggestion, but I have no need for this.  If you have it working, and it's that simple, please feel free to submit a PR or document the process in the wiki!

**Comment by JRWR** [comment]
Sounds like a plan, we can add it to be apart of docker-compose, just need to edit puma so it can be controlled and restarted when the certs get updated

**Comment by paullj1** [comment]
So I've taken a different direction to push this off on another project.  Recommend using a reverse proxy in front of this app that does let's encrypt for you (like [Caddy](https://caddyserver.com).)  Managing the cert renewal as part of this app adds a lot of complexity, and isn't really HTA's role.
