### ISSUE TITLE
Order of Challenges

### ISSUE THREAD

**Issue by JRWR** [mcpa-stlouis/hack-the-arch#48]
![image](https://user-images.githubusercontent.com/804052/36395452-3c517440-1587-11e8-87ee-7422a5d1e5e6.png)
This is annoying... I swear its pure random.

**Comment by paullj1** [comment]
This is an easy fix... currently it's just ordered by category, then points.  It expects Jeopardy style, where there's only one challenge worth 500 points in a category.  I'll push a commit for this in a minute.
